version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: compress code
          command : |
               ls -ltr
               git clone git@github.com:deep2131/repo.git
               ls 
               cd repo
               cd build
               ls
               cp -r * .
               
               
               
          
          
          
          
         # tar -cvf artifact.tar python-flask
