version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: compress code
          command : |
               ls -ltr
               mkdir code
               cp  -r ~/python-flask/* ~/code/
               
               
          
          
          
          
         # tar -cvf artifact.tar python-flask
