version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: compress code
          command : tar -cvf buildartifact.tar *
                
               
               
               
          
          
          
          
         # tar -cvf artifact.tar python-flask
