version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: compress code
          command : |
               ls -ltr
               cd ..
               mkdir code
               cd code 
               ls
             #  cp -r ../python-flask .
               
               
          
          
          
          
         # tar -cvf artifact.tar python-flask
