version: 2.1
jobs:
  compress:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: compress code
          command : tar -cvf artifact.tar python-flask
